//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporatePackage
    {
        public int Id { get; set; }
        public int RentalType_Id { get; set; }
        public int VehicleModel_Id { get; set; }
        public double Fare { get; set; }
        public int MinKm { get; set; }
        public int MinHrs { get; set; }
        public double ExtraPerHour { get; set; }
        public double ExtraPerKm { get; set; }
        public double NightCharges { get; set; }
        public int ChauffeurTaDa { get; set; }
        public bool IsActive { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public double InterStateCharge { get; set; }
        public double OutStationCharge { get; set; }
        public string PickupLocation { get; set; }
        public string DropLocation { get; set; }
        public int NoOfDays { get; set; }
    }
}
