//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPackageRouteEntry
    {
        public int Id { get; set; }
        public int MonthlyPackageRoute_Id { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string CabNo { get; set; }
        public Nullable<System.TimeSpan> PickupTime { get; set; }
        public string PickupPlace { get; set; }
        public Nullable<System.TimeSpan> DropTime { get; set; }
        public string DropPlace { get; set; }
        public int Driver_Id { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int UpdatedBy_Id { get; set; }
        public int Cab_Id { get; set; }
        public Nullable<System.DateTime> JourneyClosingDate { get; set; }
        public System.DateTime PickupDate { get; set; }
        public System.DateTime DropDate { get; set; }
        public double Toll { get; set; }
        public double MCD { get; set; }
        public System.DateTime JourneyStartDate { get; set; }
    }
}
