//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPackage
    {
        public int Id { get; set; }
        public int Customer_Id { get; set; }
        public int CreatedBy_Id { get; set; }
        public Nullable<int> UpdatedBy_Id { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string BookedBy { get; set; }
        public int VehicleModel_Id { get; set; }
        public int Cab_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int NoOfDays { get; set; }
        public int FixedKms { get; set; }
        public int FixedHourPerDay { get; set; }
        public double ExtraKmRate { get; set; }
        public double ExtraHourRate { get; set; }
        public System.TimeSpan NightStartTime { get; set; }
        public System.TimeSpan NightEndTime { get; set; }
        public double NightCharge { get; set; }
        public bool IsClosed { get; set; }
        public double Fare { get; set; }
    }
}
