//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPackageEntry
    {
        public int Id { get; set; }
        public int MonthlyPackage_Id { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string CabNo { get; set; }
        public int StKm { get; set; }
        public int EndKm { get; set; }
        public int ExtraKm { get; set; }
        public System.TimeSpan StartHr { get; set; }
        public System.TimeSpan EndHr { get; set; }
        public double ExtraHr { get; set; }
        public double NightRate { get; set; }
        public int TotalNight { get; set; }
        public double NightCharge { get; set; }
        public double TollCharge { get; set; }
        public double ParkingCharge { get; set; }
        public double MCD { get; set; }
        public double InterStateTax { get; set; }
        public int Cab_Id { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int UpdatedBy_Id { get; set; }
        public double TotalKm { get; set; }
        public double TotalHrs { get; set; }
        public double MinHrs { get; set; }
        public double ExtraHrsRate { get; set; }
        public double ExtraHrsCharge { get; set; }
        public double NetAmount { get; set; }
        public double Total { get; set; }
        public System.DateTime JourneyStartDate { get; set; }
        public int Driver_Id { get; set; }
        public Nullable<System.DateTime> JourneyClosingDate { get; set; }
    }
}
