//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPackageRoute
    {
        public int Id { get; set; }
        public int Customer_Id { get; set; }
        public int UpdatedBy_Id { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string BookedBy { get; set; }
        public int VehicleModel_Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public double Amount { get; set; }
        public bool IsClosed { get; set; }
        public int CreatedBy_Id { get; set; }
        public int MonthlyRoutePackageMaster_Id { get; set; }
        public System.DateTime BookingStartDate { get; set; }
        public System.DateTime BookingEndDate { get; set; }
        public System.TimeSpan PickupTime { get; set; }
    }
}
