//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultipleBookingFile
    {
        public int Id { get; set; }
        public int Customer_Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ConfirmationFile { get; set; }
    }
}
