//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalType
    {
        public int Id { get; set; }
        public string RentalTypeName { get; set; }
        public int PackageType_Id { get; set; }
    }
}
