//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareLink_15052023
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public bool IsHeading { get; set; }
        public bool IsMenu { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public int Counts { get; set; }
    }
}
