//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessType
    {
        public int Id { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<int> HeadingId { get; set; }
        public Nullable<int> SubHeadingId { get; set; }
        public Nullable<bool> IsHeadingRead { get; set; }
        public Nullable<bool> IsHeadingWrite { get; set; }
        public Nullable<bool> IsSubHeadingRead { get; set; }
        public Nullable<bool> IsSubHeadingWrite { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
