//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllRoute
    {
        public int Id { get; set; }
        public Nullable<int> Routing_Id { get; set; }
        public Nullable<long> RouteId { get; set; }
        public string Employee_Id { get; set; }
        public Nullable<long> RouteNameId { get; set; }
        public Nullable<int> AvailableSeats { get; set; }
        public string CabNumber { get; set; }
    }
}
