//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cab
    {
        public int Id { get; set; }
        public int Vendor_Id { get; set; }
        public string Company { get; set; }
        public string VehicleNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime FitnessVality { get; set; }
        public System.DateTime PolutionValidity { get; set; }
        public System.DateTime InsurranceValidity { get; set; }
        public string FitnessDoc { get; set; }
        public string PolutionDoc { get; set; }
        public string InsuranceDoc { get; set; }
        public string RCDoc { get; set; }
        public bool IsActive { get; set; }
        public double FuelEfficiency { get; set; }
        public int VehicleModel_Id { get; set; }
        public bool IsAvailable { get; set; }
        public string PermitNo { get; set; }
        public string PermitDoc { get; set; }
        public System.DateTime PermitValidity { get; set; }
        public string RcNumber { get; set; }
        public Nullable<System.DateTime> RcValidity { get; set; }
        public Nullable<System.DateTime> RcIssueDate { get; set; }
        public bool IsOutsider { get; set; }
    }
}
