//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string ProfilePic { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string FullAddress { get; set; }
        public bool IsActive { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string AlternateNo { get; set; }
        public Nullable<int> ParentCustomer_Id { get; set; }
        public string CompanyName { get; set; }
        public string GSTIN { get; set; }
        public int State_Id { get; set; }
        public int UserLogin_Id { get; set; }
        public Nullable<int> City_Id { get; set; }
    }
}
