//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRequest
    {
        public int Id { get; set; }
        public string RequestType { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string EmployeeId { get; set; }
        public string Unit { get; set; }
        public string Department { get; set; }
        public string CostCentre { get; set; }
        public string ExpenseCode { get; set; }
        public string RequestorEmpId { get; set; }
        public string RequestorName { get; set; }
        public string RequestorContacts { get; set; }
        public Nullable<System.DateTime> BookingReceivedDate { get; set; }
        public string RequestTripType { get; set; }
        public string DestinationRequestMethod { get; set; }
        public string LocationType { get; set; }
        public Nullable<System.DateTime> StartRequestDate { get; set; }
        public Nullable<System.DateTime> EndRequestDate { get; set; }
        public Nullable<int> TripType { get; set; }
        public Nullable<int> ShiftType { get; set; }
        public string PickupLocation { get; set; }
        public string DropLocation { get; set; }
        public string SMSTriggeredLocation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> PickupShiftTimeId { get; set; }
        public Nullable<int> DropShiftTimeId { get; set; }
        public Nullable<bool> IsRouting { get; set; }
    }
}
