//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string Company_location { get; set; }
        public string Employee_Id { get; set; }
        public string Employee_First_Name { get; set; }
        public string Employee_Middle_Name { get; set; }
        public string Employee_Last_Name { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string EmployeeCurrentAddress { get; set; }
        public string LoginUserName { get; set; }
        public string WeekOff { get; set; }
        public string EmployeeGeoCode { get; set; }
        public string EmployeeBusinessUnit { get; set; }
        public string EmployeeDepartment { get; set; }
        public string EmployeeProjectName { get; set; }
        public string ReportingManager { get; set; }
        public Nullable<int> PrimaryFacilityZone { get; set; }
        public Nullable<int> HomeRouteName { get; set; }
        public Nullable<int> EmployeeDestinationArea { get; set; }
        public Nullable<int> EmployeeRegistrationType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsFirst { get; set; }
        public Nullable<int> OTP { get; set; }
        public string Gender { get; set; }
        public string AlternateNumber { get; set; }
        public string DeviceId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string ReportingManagerEmployeeId { get; set; }
        public Nullable<double> CurrentLat { get; set; }
        public Nullable<double> CurrentLong { get; set; }
    }
}
