//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escort
    {
        public int Id { get; set; }
        public string EscortName { get; set; }
        public string EscortFatheName { get; set; }
        public string EscortMobileNumber { get; set; }
        public string EscortAadhaarNumber { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EscortEmployeeId { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string PermanentAddress { get; set; }
        public string EscortAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
