//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPackageRouteMaster
    {
        public int Id { get; set; }
        public int VehicleModel_Id { get; set; }
        public string PickupLocation { get; set; }
        public string DropLocation { get; set; }
        public double Fare { get; set; }
        public int NoOfDays { get; set; }
        public int UpdatedBy_Id { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
