//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPackageRouteBill
    {
        public int Id { get; set; }
        public int MonthlyPackageRoute_Id { get; set; }
        public string BillFile { get; set; }
        public string BillNumber { get; set; }
        public bool IsCancelled { get; set; }
        public double Fare { get; set; }
        public int NoOfDays { get; set; }
        public double NetAmount { get; set; }
        public double Toll { get; set; }
        public double MCD { get; set; }
        public double GstInPercent { get; set; }
        public double CGST { get; set; }
        public double SGST { get; set; }
        public double IGST { get; set; }
        public double TotalAmount { get; set; }
        public int BillingState_Id { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int UpdatedBy_Id { get; set; }
        public System.DateTime BillDate { get; set; }
    }
}
