//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NrgPackage
    {
        public int Id { get; set; }
        public int RentalType_Id { get; set; }
        public int VehicleModel_Id { get; set; }
        public double Fare { get; set; }
        public int MinKm { get; set; }
        public int MinHrs { get; set; }
        public int ExtraPerHour { get; set; }
        public int ExtraPerKm { get; set; }
        public int NightCharges { get; set; }
        public int ChauffeurTaDa { get; set; }
        public bool IsActive { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public double InterStateCharge { get; set; }
        public double OutStationCharge { get; set; }
    }
}
