//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupAndDropLocationData
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> RouteDate { get; set; }
        public Nullable<int> CabId { get; set; }
        public Nullable<int> TripTypeid { get; set; }
        public Nullable<int> PickupShiftId { get; set; }
        public Nullable<int> DropShiftId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public string PickupLocation { get; set; }
        public string DropLocation { get; set; }
        public string Employee_Id { get; set; }
        public Nullable<long> DriverId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> AllRoute_Id { get; set; }
    }
}
