//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routing
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> RouteStartDate { get; set; }
        public Nullable<System.DateTime> RouteEndDate { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> TripType { get; set; }
        public string PickupShiftTime { get; set; }
        public string DropShiftTime { get; set; }
        public string AdhocShiftTime { get; set; }
        public string VehicleType { get; set; }
        public string Routingtype { get; set; }
        public string RoutingOption { get; set; }
    }
}
