//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public int Id { get; set; }
        public string Head_Office { get; set; }
        public string Branch_One { get; set; }
        public string Branch_Two { get; set; }
        public string Branch_Three { get; set; }
        public string Employee_ContactNumber { get; set; }
        public string Driver_ContactNumber { get; set; }
        public string Email_Id { get; set; }
        public string Website_URL { get; set; }
        public string Employee_EmergencyNumber { get; set; }
        public string Driver_EmergencyNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
