//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempUserBooking
    {
        public int Id { get; set; }
        public int BookingId { get; set; }
        public string Username { get; set; }
        public string SessionId { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
