//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorBill
    {
        public int Id { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int Booking_Id { get; set; }
        public double CGST { get; set; }
        public double SGST { get; set; }
        public double IGST { get; set; }
        public int Company_Id { get; set; }
        public string GuestName { get; set; }
        public string DutyAddress { get; set; }
        public string DsNo { get; set; }
        public System.DateTime DsDate { get; set; }
        public int StartKms { get; set; }
        public int EndKms { get; set; }
        public double TotalHrs { get; set; }
        public int ExtraKms { get; set; }
        public double ExtraKmsRate { get; set; }
        public double ExtraKmsCharge { get; set; }
        public double ExtraHrs { get; set; }
        public double ExtraHrsRate { get; set; }
        public double ExtraHrsCharge { get; set; }
        public double Total { get; set; }
        public int StateGstin_Id { get; set; }
        public double FuelCharge { get; set; }
        public double Fare { get; set; }
        public double NightCharge { get; set; }
        public double MinKm { get; set; }
        public double MinHrs { get; set; }
        public double TotalKms { get; set; }
        public double IncreaseDecreaseInFuel { get; set; }
        public double FuelEfficiency { get; set; }
        public int TotalNight { get; set; }
        public System.TimeSpan StartHour { get; set; }
        public System.TimeSpan EndHour { get; set; }
        public double ParkCharge { get; set; }
        public double TollCharge { get; set; }
        public double StateCharge { get; set; }
        public double NightRate { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> JourneyStartDate { get; set; }
        public Nullable<System.DateTime> JourneyClosingDate { get; set; }
        public double IgstPercent { get; set; }
        public double CgstPercent { get; set; }
        public double SgstPercent { get; set; }
        public string BillFile { get; set; }
        public double InterStateCharge { get; set; }
        public double OutStationCharge { get; set; }
        public double OutStationChargeRate { get; set; }
        public double OutStationDays { get; set; }
        public double VendorCommision { get; set; }
        public double MCD { get; set; }
        public string VisitedPlace { get; set; }
        public double MiscCharge { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> NetAmount { get; set; }
    }
}
