//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VardaanCab.DataAccessLayer.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int Id { get; set; }
        public string VendorName { get; set; }
        public int CityMaster_Id { get; set; }
        public int StateMaster_Id { get; set; }
        public string FullAddress { get; set; }
        public string AlernateMobile { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ParentVendor_Id { get; set; }
        public bool IsActive { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string GSTIN { get; set; }
        public string PAN { get; set; }
        public string CIN { get; set; }
        public string PanImage { get; set; }
        public bool IsOutsider { get; set; }
        public Nullable<int> Company_Id { get; set; }
    }
}
